[development]
api_key = "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"
user = "postgres"
password = "newskill@26"

[production]
api_key = "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"
user = "postgres"
password = "newskill@26"